version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=webservice
